import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
test('export records ownership and refuses local changes before any replacement',t=>{
 const dir=mkdtempSync(join(tmpdir(),'pelizzai-export-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const run=()=>spawnSync(process.execPath,[join(root,'scripts/sync-harness.mjs'),'--export-consumer',dir],{encoding:'utf8'});
 let result=run();assert.equal(result.status,0,result.stderr);
 const receipt=join(dir,'scripts/pelizzai-installation.json'), first=readFileSync(receipt,'utf8');
 assert.equal(JSON.parse(first).schema,1);
 assert.equal(existsSync(join(dir,'scripts/project-memory.mjs')),true);
 result=run();assert.equal(result.status,0,result.stderr);assert.equal(readFileSync(receipt,'utf8'),first);
 writeFileSync(receipt,'{incomplete');
 const invalid=run();assert.equal(invalid.status,1);assert.match(invalid.stderr,/Invalid installation receipt.*reconcile/);
 assert.equal(readFileSync(receipt,'utf8'),'{incomplete');writeFileSync(receipt,first);
 const skill=join(dir,'.claude/skills/pelizzai-core/SKILL.md');
 const original=readFileSync(skill,'utf8');writeFileSync(skill,original+'\nLocal custom rule\n');
 assert.equal(run().status,1);assert.match(readFileSync(skill,'utf8'),/Local custom rule/);assert.equal(readFileSync(receipt,'utf8'),first);
 writeFileSync(skill,original);
 const extra=join(dir,'.claude/skills/pelizzai-core/local-reference.md');writeFileSync(extra,'Keep this local evidence');
 assert.equal(run().status,1);assert.equal(readFileSync(extra,'utf8'),'Keep this local evidence');
 rmSync(extra);
 const localTest=join(dir,'scripts/test-harness-contracts.ps1');writeFileSync(localTest,'local test');
 assert.equal(run().status,0);assert.equal(readFileSync(localTest,'utf8'),'local test');
 const domain=join(dir,'.agents/skills/local-domain');mkdirSync(domain);
 writeFileSync(join(domain,'SKILL.md'),'My Codex-only domain');
 assert.equal(run().status,1);assert.equal(readFileSync(join(domain,'SKILL.md'),'utf8'),'My Codex-only domain');
 rmSync(domain,{recursive:true});
 const mirrorNote=join(dir,'.agents/skills/notes.md');writeFileSync(mirrorNote,'Local root note');
 assert.equal(run().status,1);assert.equal(readFileSync(mirrorNote,'utf8'),'Local root note');
 rmSync(mirrorNote);
 const prefixedNote=join(dir,'.agents/skills/pelizzai-local-notes.md');writeFileSync(prefixedNote,'Prefixed local note');
 assert.equal(run().status,1);assert.equal(readFileSync(prefixedNote,'utf8'),'Prefixed local note');
});
