import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {buildIndex,searchMemory} from '../../scripts/project-memory.mjs';
test('retrieval reaches archives, keeps active rules, and revalidates changed knowledge',t=>{
 const dir=mkdtempSync(join(tmpdir(),'pelizzai-memory-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 mkdirSync(join(dir,'pelizzai/data/history'),{recursive:true});
 writeFileSync(join(dir,'pelizzai/data/learnings.md'),'# Learnings\n## Active rules\n- Confirm storage ownership before deletion.\n## Incident log\nUnrelated incident.');
 writeFileSync(join(dir,'pelizzai/data/history/old.md'),'# Prior delivery\nOAuth picture reused a production bucket.\ncause: storage/ownership\n');
 const index=buildIndex(dir), result=searchMemory(index,'OAuth bucket');
 assert.equal(result.matches[0].path,'pelizzai/data/history/old.md');
 assert.equal(result.matches[0].kind,'historical');
 assert.match(result.activeRules,/Confirm storage/);assert.doesNotMatch(result.activeRules,/Unrelated/);
 assert.equal(searchMemory(index,'unfindable-term').matches.length,0);
 writeFileSync(join(dir,'pelizzai/data/history/new.md'),'# New incident\nOAuth failure\n');
 const updated=buildIndex(dir);assert.notEqual(updated.corpusHash,index.corpusHash);
 assert.equal(searchMemory(updated,'OAuth').matches.length,2);
 assert.equal(existsSync(join(dir,'pelizzai/data/memory-index.json')),false);
 writeFileSync(join(dir,'pelizzai/data/learnings.md'),'# Aprendizados\n## Regras ativas\n- Conferir propriedade antes de remover.\n## Incidentes\nOutro incidente.');
 const legacy=searchMemory(buildIndex(dir),'OAuth');
 assert.equal(legacy.activeRulesStatus,'recognized');
 assert.match(legacy.activeRules,/Conferir propriedade/);assert.doesNotMatch(legacy.activeRules,/Outro incidente/);
 writeFileSync(join(dir,'pelizzai/data/learnings.md'),'# Custom layout\nAlways preserve storage ownership.');
 const unknown=searchMemory(buildIndex(dir),'OAuth');
 assert.equal(unknown.activeRulesStatus,'unrecognized-heading-read-full-source');
 assert.match(unknown.activeRules,/Always preserve/);
});
